apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  labels:
    end: front
spec:
  replicas: 2
  selector:
    matchLabels:
      end: front
  template:
    metadata:
      labels:
        end: front
    spec:
      containers:
      - name: borodun-front-container
        image: borodun/api-async-front
        ports:
        - containerPort: 80
        env:
        - name: API_BASE_URL
          value: http://45.9.24.10:32223/v1
